import { ReactNode } from 'react'
import clsx from 'clsx'
import type { Metadata } from 'next'

import TranslateProvider from '@/components/Providers'
import TranslateText from '@/components/translateText'
import { fontSans } from '@/config/fonts'

import { Providers } from './providers'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale}>
      <body className={clsx('font-sans antialiased', fontSans.className)}>
        <TranslateProvider>
          <Providers>
            <TranslateText />
            {children}
          </Providers>
        </TranslateProvider>
      </body>
    </html>
  )
}
