import { ReactNode } from 'react'
import { Toaster } from 'react-hot-toast'
import clsx from 'clsx'
import type { Metadata } from 'next'

import AppIntlProvider from '@/app/(providers)/AppIntlProvider'
import Layout from '@/components/Layout'
import { fontSans } from '@/config/fonts'

import { Providers } from './providers'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body className={clsx('font-sans antialiased', fontSans.className)}>
        <AppIntlProvider>
          <Providers>
            <Toaster position="top-right" reverseOrder={false} />
            <Layout>{children}</Layout>
          </Providers>
        </AppIntlProvider>
      </body>
    </html>
  )
}
