import { TestConfig } from '@/components/TestsQuestionnarie/typesTestPage'

const stressTestQuestions = [
  { id: 'int-1', text: 'Переважання негативних думок', group: 'intellectual' },
  { id: 'int-2', text: 'Труднощі зосередження', group: 'intellectual' },
  { id: 'int-3', text: "Погіршення показників пам'яті", group: 'intellectual' },
  { id: 'int-4', text: 'Постійне і безплідне обертання думок навколо однієї проблеми', group: 'intellectual' },
  { id: 'int-5', text: 'Підвищена відволікання', group: 'intellectual' },
  { id: 'int-6', text: 'Труднощі прийняття рішень, тривалі коливання при виборі', group: 'intellectual' },
  { id: 'int-7', text: 'Погані сни, кошмари', group: 'intellectual' },
  { id: 'int-8', text: 'Часті помилки, збої в обчисленнях', group: 'intellectual' },
  { id: 'int-9', text: 'Пасивність, бажання перекласти відповідальність на когось іншого', group: 'intellectual' },
  { id: 'int-10', text: 'Порушення логіки, сплутане мислення', group: 'intellectual' },
  { id: 'int-11', text: 'Імпульсивність мислення, поспішні і необґрунтовані рішення', group: 'intellectual' },
  { id: 'int-12', text: 'Звуження «поля зору», коли “бачиться” менше можливих варіантів дії', group: 'intellectual' },

  { id: 'beh-1', text: 'Втрата апетиту або переїдання', group: 'behavioral' },
  { id: 'beh-2', text: 'Зростання помилок при виконанні звичних дій', group: 'behavioral' },
  { id: 'beh-3', text: 'Більш швидка або, навпаки, уповільнена мова', group: 'behavioral' },
  { id: 'beh-4', text: 'Тремтіння голосу', group: 'behavioral' },
  { id: 'beh-5', text: "Збільшення конфліктних ситуацій на роботі або в сім'ї", group: 'behavioral' },
  { id: 'beh-6', text: 'Хронічна нестача часу', group: 'behavioral' },
  { id: 'beh-7', text: 'Зменшення часу, що приділяється на спілкування з близькими і друзями', group: 'behavioral' },
  { id: 'beh-8', text: 'Втрата уваги до свого зовнішнього вигляду, неухоженность', group: 'behavioral' },
  { id: 'beh-9', text: 'Антисоціальна, конфліктна поведінка', group: 'behavioral' },
  { id: 'beh-10', text: 'Низька продуктивність діяльності', group: 'behavioral' },
  { id: 'beh-11', text: 'Порушення сну або безсоння', group: 'behavioral' },
  { id: 'beh-12', text: 'Більш інтенсивне куріння і вживання алкоголю', group: 'behavioral' },

  { id: 'emo-1', text: 'Занепокоєння, підвищена тривожність', group: 'emotional' },
  { id: 'emo-2', text: 'Підозрілість', group: 'emotional' },
  { id: 'emo-3', text: 'Похмурий настрій', group: 'emotional' },
  { id: 'emo-4', text: 'Відчуття постійної туги, депресія', group: 'emotional' },
  { id: 'emo-5', text: 'Дратівливість, напади гніву', group: 'emotional' },
  { id: 'emo-6', text: 'Емоційна «тупість», байдужість', group: 'emotional' },
  { id: 'emo-7', text: 'Цинічний, недоречний гумор', group: 'emotional' },
  { id: 'emo-8', text: 'Зменшення почуття впевненості в собі', group: 'emotional' },
  { id: 'emo-9', text: 'Зменшення задоволеності життям', group: 'emotional' },
  { id: 'emo-10', text: 'Почуття відчуженості, самотності', group: 'emotional' },
  { id: 'emo-11', text: 'Втрата інтересу до життя', group: 'emotional' },
  {
    id: 'emo-12',
    text: 'Зниження самооцінки, поява почуття провини або невдоволення собою або своєю роботою',
    group: 'emotional',
  },
  { id: 'phy-1', text: 'Болі в різних частинах тіла невизначеного характеру, головні болі', group: 'physiological' },
  { id: 'phy-2', text: 'Підвищення або зниження артеріального тиску', group: 'physiological' },
  { id: 'phy-3', text: 'Прискорений або неритмічний пульс', group: 'physiological' },
  {
    id: 'phy-4',
    text: 'Порушення процесів травлення (запор, діарея, підвищене газоутворення)',
    group: 'physiological',
  },
  { id: 'phy-5', text: 'Порушення свободи дихання', group: 'physiological' },
  { id: 'phy-6', text: "Відчуття напруги в м'язах", group: 'physiological' },
  { id: 'phy-7', text: 'Підвищена стомлюваність', group: 'physiological' },
  { id: 'phy-8', text: 'Тремтіння в руках, судоми', group: 'physiological' },
  { id: 'phy-9', text: 'Поява алергії чи інших шкірних висипань', group: 'physiological' },
  { id: 'phy-10', text: 'Підвищена пітливість', group: 'physiological' },
  { id: 'phy-11', text: 'Швидке збільшення або втрата ваги тіла', group: 'physiological' },
  { id: 'phy-12', text: 'Зниження імунітету, часті нездужання', group: 'physiological' },
]

const stressTest: TestConfig<'checkbox'> = {
  id: 'scherbatih',
  title: 'Тест на рівень стресу (Щербатих)',
  type: 'checkbox',
  groupWeights: {
    intellectual: 1,
    behavioral: 1,
    emotional: 1.5,
    physiological: 2,
  },
  questions: stressTestQuestions.map((obj) => ({
    id: obj.id,
    text: obj.text,
    group: obj.group,
  })),
  scoring: { groupWeight: true },
  resultMapping: [
    { min: 0, max: 5, label: 'Низький рівень стресу' },
    { min: 6, max: 12, label: 'Помірний рівень стресу' },
    { min: 13, max: 24, label: 'Виражене напруження — варто звернутися' },
    { min: 25, max: 40, label: 'Сильний стрес — консультація бажана' },
    { min: 41, max: Infinity, label: 'Виснаження — необхідна допомога' },
  ],
}

export default stressTest
