name: Run Cypress Tests on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  cypress-tests:
    if: contains(github.event.pull_request.labels.*.name, 'Run Cypress Tests')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start the application
        run: |
          nohup yarn dev &
          sleep 5

      - name: Wait for the server to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: yarn cypress run
        env:
          CYPRESS_BASE_URL: http://localhost:3000
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
