name: Frontend Run Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      folder: ${{ steps.filter.outputs.folder }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            folder:
              - 'app/**'
              - 'components/**'
              - 'public/**'
              - 'styles/**'
              - 'utils/**'

  linters:
    needs: check-file-changes
    if: needs.check-file-changes.outputs.folder != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Prettier Check
        run: yarn prettier

      - name: TS Check
        run: yarn tsc

      - name: Run Tests
        run: yarn test

  assign-reviewers:
    runs-on: ubuntu-latest
    needs: linters
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn add @actions/core @actions/github
        working-directory: .github/scripts

      - name: Add Reviewers
        run: node .github/scripts/add-reviewers.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
